repos:
  - repo: https://github.com/psf/black
    rev: 25.12.0
    hooks:
      - id: black
        name: black (code formatting)
        files: ^(bluez_peripheral/|tests/)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        name: mypy (type hints)
        additional_dependencies:
          - dbus_fast
        files: ^bluez_peripheral/

  - repo: https://github.com/pylint-dev/pylint
    rev: v4.0.4
    hooks:
      - id: pylint
        additional_dependencies:
          - dbus_fast
        files: ^bluez_peripheral/

  - repo: local
    hooks:
      - id: docs-build
        name: docs (build)
        entry: bash -c "cd docs && make clean && make html"
        language: system
        pass_filenames: false
        stages: [manual]

      - id: docs-spelling
        name: docs (spell check)
        entry: bash -c "cd docs && make spelling"
        language: system
        pass_filenames: false
        stages: [manual]

      - id: docs-doctest
        name: docs (test code snippets)
        entry: bash -c "cd docs && make doctest"
        language: system
        pass_filenames: false
        stages: [manual]

      - id: docs-linkcheck
        name: docs (linkcheck)
        entry: bash -c "cd docs && make linkcheck"
        language: system
        pass_filenames: false
        stages: [manual]
